In [1]:
import numpy as np 

In [6]:
#Create two square matrix, ( use brackets to create rows) ('\n' prints a jump)

x = np.array([[1,5,6],[8,5,9],[1,0,3]])
z = np.array([[12,20,-3],[5,-8,5],[6,9,17]])

print(x,'\n')
print(z)

[[1 5 6]
 [8 5 9]
 [1 0 3]] 

[[12 20 -3]
 [ 5 -8  5]
 [ 6  9 17]]


In [7]:
# Add and subtract the matrixes x and z 

r_added = x.__add__(z)
r_sub = x.__sub__(z)

print(r_added,'\n')
print(r_sub,'\n')

[[13 25  3]
 [13 -3 14]
 [ 7  9 20]] 

[[-11 -15   9]
 [  3  13   4]
 [ -5  -9 -14]] 



In [8]:
#Piecewise multiplication and multiplication of two matrixes 
#(matmul is mathematic multiplication) (mul is just multiplication)
#matmul takes the first row and multiplicates it with the first column

r_piecewise = x.__mul__(z)

r_mul = x.__matmul__(z)

print(r_piecewise,'\n')
print(r_mul)

[[ 12 100 -18]
 [ 40 -40  45]
 [  6   0  51]] 

[[ 73  34 124]
 [175 201 154]
 [ 30  47  48]]


In [15]:
# 1x + 1y = 2 and 10x + 35y = 30 ( Brackets establish rows)

A = np.array([[1, 1],[10, 35]])
B = np.array([[2],[30]])

In [16]:
#Verify size of the matrix A and B (DImensions)

print('dim. of matrix A =' ,A.shape)
print('dim. of vector b =' ,B.shape)

dim. of matrix A = (2, 2)
dim. of vector b = (2, 1)


In [17]:
# Find the det(A)

np.linalg.det(A)

25.000000000000007

In [18]:
# Find the inverse of det(A)

inv_A = np.linalg.inv(A)
print(inv_A)

[[ 1.4  -0.04]
 [-0.4   0.04]]


In [19]:
#FInding the solution for x and y 

solution = inv_A.dot(B)
print(solution)

[[1.6]
 [0.4]]


In [20]:
#verify our results 1x+1y=2 anf 10x+35y=30

print(1*1.6 + 1*0.4, '\n')

print(10*1.6 + 35*0.4, '\n')

2.0 

30.0 

